language: scala
jdk:
  - oraclejdk8
sudo: false
scala:
  - 2.11.8
services:
  - docker
env:
  - DOCKERIMAGE=rfc1149/couchdb:1.x.x
  - DOCKERIMAGE=klaemo/couchdb:2.0.0
before_install:
  - docker run -d -p 5984:5984 $DOCKERIMAGE
script:
  - sbt clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
