language: scala
branches:
  only:
    - staging
    - trying
jdk:
  - oraclejdk8
  - oraclejdk11
sudo: false
scala:
  - 2.12.8
services:
  - couchdb
env:
  global:
    secure: ALtSdAp4wFe55/RY2+XYL8zkpwmxlIUpklbfIVzfvB+8rMMOyRxDnVbQX8DAZEqgTvQpddghOJLbqJTXwfF1MuuSVMsRpa8/iCgl6dB4fCv4YlHaLK0mb96ca0vFV0dUnp+gy9u3tNkuVAWzqlDkPf2lMreYkKlNqiqGELsFOp4=
script:
  - sbt clean coverage test coverageReport
cache:
  directories:
    - $HOME/.ivy2/cache
