name: Validation process
on:
  push:
    branches:
      - staging
      - trying
      - renovate/**
  pull_request:
  merge_group:
jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        couchdb_version: ['2.3.1']
      fail-fast: false
    steps:
      - name: Get Ivy2 cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2
          key: ivy2-files
      - name: Checkout
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
      - name: Setup CouchDB
        uses: "cobot/couchdb-action@master"
        with:
          couchdb version: ${{ matrix.couchdb_version }}
      - name: SBT tests and artifacts
        run: sbt test
